name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./GithubActionsSample
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./GithubActionsSample
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: ./GithubActionsSample
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool  
    - name: Generate Coverage Report
      run: /root/.dotnet/tools/reportgenerator -reports:`find .  -type f -name "coverage.cobertura.xml"` -targetdir:"CoverageReport" -reporttypes:Html
      working-directory: ./GithubActionsSample
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: GithubActionsSample/CoverageReport
