name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./GithubActionsSample
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./GithubActionsSample
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: ./GithubActionsSample
    - name: Find CoverageReport
      run: |
          report=`find . -type f -name "coverage.cobertura.xml"`
          echo "::set-output name=CoverageReportPath::${report}"
      id: FindReport
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.0.4
      with:
        reports: '${{ steps.FindReport.outputs.CoverageReportPath }}'
        targetdir: 'CoverageReport'
        reporttypes: 'Html'
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: GithubActionsSample/CoverageReport
